/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module autoTester_6 (
    input clk,
    input rst,
    input proceed,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel
  );
  
  
  
  wire [3-1:0] M_alu_tester_out;
  wire [2-1:0] M_alu_tester_indicator;
  wire [8-1:0] M_alu_tester_counter_indicator;
  wire [4-1:0] M_alu_tester_state_indicator;
  reg [1-1:0] M_alu_tester_proceed;
  aluTester_12 alu_tester (
    .clk(clk),
    .rst(rst),
    .proceed(M_alu_tester_proceed),
    .out(M_alu_tester_out),
    .indicator(M_alu_tester_indicator),
    .counter_indicator(M_alu_tester_counter_indicator),
    .state_indicator(M_alu_tester_state_indicator)
  );
  
  always @* begin
    io_led[0+0+2-:3] = M_alu_tester_out;
    io_led[8+0+1-:2] = M_alu_tester_indicator;
    io_led[8+4+3-:4] = M_alu_tester_state_indicator;
    io_led[16+7-:8] = M_alu_tester_counter_indicator;
    io_sel = 4'h0;
    M_alu_tester_proceed = proceed;
    if (M_alu_tester_indicator[0+0-:1] == 1'h1) begin
      if (M_alu_tester_indicator[1+0-:1] == 1'h0) begin
        io_seg = 8'h0e;
      end else begin
        io_seg = 8'h12;
      end
    end
  end
endmodule
