/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module booleanTester_20 (
    input clk,
    input rst,
    input start,
    input error,
    output reg [1:0] indicator,
    output reg [3:0] state_indicator,
    output reg [7:0] counter_indicator
  );
  
  
  
  reg [3:0] M_counter_d, M_counter_q = 1'h0;
  
  
  localparam SLEEP_state = 2'd0;
  localparam TEST_state = 2'd1;
  localparam PASS_state = 2'd2;
  localparam FAIL_state = 2'd3;
  
  reg [1:0] M_state_d, M_state_q = SLEEP_state;
  
  wire [16-1:0] M_booleanUnit_out;
  reg [16-1:0] M_booleanUnit_x;
  reg [16-1:0] M_booleanUnit_y;
  reg [6-1:0] M_booleanUnit_alufn;
  boolean_14 booleanUnit (
    .x(M_booleanUnit_x),
    .y(M_booleanUnit_y),
    .alufn(M_booleanUnit_alufn),
    .out(M_booleanUnit_out)
  );
  
  always @* begin
    M_state_d = M_state_q;
    M_counter_d = M_counter_q;
    
    indicator = 2'h2;
    M_booleanUnit_x = 16'h0000;
    M_booleanUnit_y = 16'h0000;
    M_booleanUnit_alufn = 6'h00;
    if (start == 1'h0) begin
      M_state_d = SLEEP_state;
      M_counter_d = 1'h0;
    end
    
    case (M_state_q)
      SLEEP_state: begin
        if (start == 1'h1) begin
          M_state_d = TEST_state;
        end
      end
      TEST_state: begin
        
        case (M_counter_q)
          4'h1: begin
            M_booleanUnit_alufn = 6'h10;
            M_booleanUnit_x = 16'hf0f0;
            M_booleanUnit_y = 16'hff0f;
            if (error == 1'h1) begin
              if (~M_booleanUnit_out != 16'hf000) begin
                M_state_d = FAIL_state;
              end
            end else begin
              if (M_booleanUnit_out != 16'hf000) begin
                M_state_d = FAIL_state;
              end
            end
          end
          4'h2: begin
            M_booleanUnit_alufn = 6'h11;
            M_booleanUnit_x = 16'hf0f0;
            M_booleanUnit_y = 16'hff00;
            if (M_booleanUnit_out != 16'hfff0) begin
              M_state_d = FAIL_state;
            end
          end
          4'h3: begin
            M_booleanUnit_alufn = 6'h12;
            M_booleanUnit_x = 16'hf0f0;
            M_booleanUnit_y = 16'hff00;
            if (M_booleanUnit_out != 16'h0ff0) begin
              M_state_d = FAIL_state;
            end
          end
          4'h4: begin
            M_booleanUnit_alufn = 6'h13;
            M_booleanUnit_x = 16'hf0f0;
            M_booleanUnit_y = 16'hff00;
            if (M_booleanUnit_out != 16'hf0f0) begin
              M_state_d = FAIL_state;
            end
          end
          4'h5: begin
            M_state_d = PASS_state;
          end
        endcase
      end
      PASS_state: begin
        indicator = 2'h3;
      end
      FAIL_state: begin
        indicator = 2'h1;
      end
    endcase
    if (M_state_q == TEST_state) begin
      M_counter_d = M_counter_q + 1'h1;
    end
    counter_indicator = M_counter_q;
    
    case (M_state_q)
      SLEEP_state: begin
        state_indicator = 4'h1;
      end
      TEST_state: begin
        state_indicator = 4'h2;
      end
      PASS_state: begin
        state_indicator = 4'h4;
      end
      FAIL_state: begin
        state_indicator = 4'h8;
      end
      default: begin
        state_indicator = 4'hf;
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_counter_q <= 1'h0;
    end else begin
      M_counter_q <= M_counter_d;
    end
  end
  
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_state_q <= 1'h0;
    end else begin
      M_state_q <= M_state_d;
    end
  end
  
endmodule
