/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module minimum_18 (
    input v,
    input n,
    input [15:0] x,
    input [15:0] y,
    input [5:0] alufn,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    out = 16'h0000;
    
    case (alufn[1+1-:2])
      2'h0: begin
        if (n ^ v == 1'h1) begin
          out = x;
        end else begin
          out = y;
        end
      end
      2'h1: begin
        if (n ^ v == 1'h1) begin
          out = y;
        end else begin
          out = x;
        end
      end
      default: begin
        out = 16'h0000;
      end
    endcase
  end
endmodule
