/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adderTester_19 (
    input clk,
    input rst,
    input start,
    input error,
    output reg [1:0] indicator,
    output reg [3:0] state_indicator,
    output reg [7:0] counter_indicator
  );
  
  
  
  reg [3:0] M_counter_d, M_counter_q = 1'h0;
  
  
  localparam SLEEP_state = 2'd0;
  localparam TEST_state = 2'd1;
  localparam PASS_state = 2'd2;
  localparam FAIL_state = 2'd3;
  
  reg [1:0] M_state_d, M_state_q = SLEEP_state;
  
  wire [16-1:0] M_adderUnit_out;
  wire [1-1:0] M_adderUnit_z;
  wire [1-1:0] M_adderUnit_v;
  wire [1-1:0] M_adderUnit_n;
  reg [16-1:0] M_adderUnit_x;
  reg [16-1:0] M_adderUnit_y;
  reg [6-1:0] M_adderUnit_alufn;
  adder_13 adderUnit (
    .x(M_adderUnit_x),
    .y(M_adderUnit_y),
    .alufn(M_adderUnit_alufn),
    .out(M_adderUnit_out),
    .z(M_adderUnit_z),
    .v(M_adderUnit_v),
    .n(M_adderUnit_n)
  );
  
  always @* begin
    M_state_d = M_state_q;
    M_counter_d = M_counter_q;
    
    indicator = 2'h2;
    M_adderUnit_x = 16'h0000;
    M_adderUnit_y = 16'h0000;
    M_adderUnit_alufn = 6'h00;
    if (start == 1'h0) begin
      M_state_d = SLEEP_state;
      M_counter_d = 1'h0;
    end
    
    case (M_state_q)
      SLEEP_state: begin
        if (start == 1'h1) begin
          M_state_d = TEST_state;
        end
      end
      TEST_state: begin
        
        case (M_counter_q)
          4'h1: begin
            M_adderUnit_alufn = 6'h00;
            M_adderUnit_x = 16'h0000;
            M_adderUnit_y = 16'h0000;
            if (error == 1'h1) begin
              if (~M_adderUnit_out != 16'h0000) begin
                M_state_d = FAIL_state;
              end
            end else begin
              if (M_adderUnit_out != 16'h0000) begin
                M_state_d = FAIL_state;
              end
            end
            if (M_adderUnit_z != 1'h1) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_v != 1'h0) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_n != 1'h0) begin
              M_state_d = FAIL_state;
            end
          end
          4'h2: begin
            M_adderUnit_alufn = 6'h00;
            M_adderUnit_x = 16'h7fff;
            M_adderUnit_y = 16'h0001;
            if (M_adderUnit_out != 16'h8000) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_z != 1'h0) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_v != 1'h1) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_n != 1'h1) begin
              M_state_d = FAIL_state;
            end
          end
          4'h3: begin
            M_adderUnit_alufn = 6'h00;
            M_adderUnit_x = 16'h0002;
            M_adderUnit_y = 16'h0003;
            if (M_adderUnit_out != 16'h0005) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_z != 1'h0) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_v != 1'h0) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_n != 1'h0) begin
              M_state_d = FAIL_state;
            end
          end
          4'h4: begin
            M_adderUnit_alufn = 6'h00;
            M_adderUnit_x = 16'h0002;
            M_adderUnit_y = 16'hfffd;
            if (M_adderUnit_out != 16'hffff) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_z != 1'h0) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_v != 1'h0) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_n != 1'h1) begin
              M_state_d = FAIL_state;
            end
          end
          4'h5: begin
            M_adderUnit_alufn = 6'h00;
            M_adderUnit_x = 16'h0003;
            M_adderUnit_y = 16'hfffe;
            if (M_adderUnit_out != 16'h0001) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_z != 1'h0) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_v != 1'h0) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_n != 1'h0) begin
              M_state_d = FAIL_state;
            end
          end
          4'h6: begin
            M_adderUnit_alufn = 6'h00;
            M_adderUnit_x = 16'h8001;
            M_adderUnit_y = 16'h8001;
            if (M_adderUnit_out != 16'h0002) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_z != 1'h0) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_v != 1'h1) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_n != 1'h0) begin
              M_state_d = FAIL_state;
            end
          end
          4'h7: begin
            M_adderUnit_alufn = 6'h00;
            M_adderUnit_x = 16'hfffe;
            M_adderUnit_y = 16'hfffd;
            if (M_adderUnit_out != 16'hfffb) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_z != 1'h0) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_v != 1'h0) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_n != 1'h1) begin
              M_state_d = FAIL_state;
            end
          end
          4'h8: begin
            M_adderUnit_alufn = 6'h01;
            M_adderUnit_x = 16'h0000;
            M_adderUnit_y = 16'h0000;
            if (M_adderUnit_out != 16'h0000) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_z != 1'h1) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_v != 1'h0) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_n != 1'h0) begin
              M_state_d = FAIL_state;
            end
          end
          4'h9: begin
            M_adderUnit_alufn = 6'h01;
            M_adderUnit_x = 16'h0003;
            M_adderUnit_y = 16'h0001;
            if (M_adderUnit_out != 16'h0002) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_z != 1'h0) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_v != 1'h0) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_n != 1'h0) begin
              M_state_d = FAIL_state;
            end
          end
          4'ha: begin
            M_adderUnit_alufn = 6'h01;
            M_adderUnit_x = 16'h7fff;
            M_adderUnit_y = 16'hffff;
            if (M_adderUnit_out != 16'h8000) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_z != 1'h0) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_v != 1'h1) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_n != 1'h1) begin
              M_state_d = FAIL_state;
            end
          end
          4'hb: begin
            M_adderUnit_alufn = 6'h01;
            M_adderUnit_x = 16'h0003;
            M_adderUnit_y = 16'hffff;
            if (M_adderUnit_out != 16'h0004) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_z != 1'h0) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_v != 1'h0) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_n != 1'h0) begin
              M_state_d = FAIL_state;
            end
          end
          4'hc: begin
            M_adderUnit_alufn = 6'h01;
            M_adderUnit_x = 16'hf000;
            M_adderUnit_y = 16'h7fff;
            if (M_adderUnit_out != 16'h7001) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_z != 1'h0) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_v != 1'h1) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_n != 1'h0) begin
              M_state_d = FAIL_state;
            end
          end
          4'hd: begin
            M_adderUnit_alufn = 6'h01;
            M_adderUnit_x = 16'hfff9;
            M_adderUnit_y = 16'h0001;
            if (M_adderUnit_out != 16'hfff8) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_z != 1'h0) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_v != 1'h0) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_n != 1'h1) begin
              M_state_d = FAIL_state;
            end
          end
          4'he: begin
            M_adderUnit_alufn = 6'h01;
            M_adderUnit_x = 16'hfffe;
            M_adderUnit_y = 16'hfffd;
            if (M_adderUnit_out != 16'h0001) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_z != 1'h0) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_v != 1'h0) begin
              M_state_d = FAIL_state;
            end
            if (M_adderUnit_n != 1'h0) begin
              M_state_d = FAIL_state;
            end
          end
          4'hf: begin
            M_state_d = PASS_state;
          end
        endcase
      end
      PASS_state: begin
        indicator = 2'h3;
      end
      FAIL_state: begin
        indicator = 2'h1;
      end
    endcase
    if (M_state_q == TEST_state) begin
      M_counter_d = M_counter_q + 1'h1;
    end
    counter_indicator = M_counter_q;
    
    case (M_state_q)
      SLEEP_state: begin
        state_indicator = 4'h1;
      end
      TEST_state: begin
        state_indicator = 4'h2;
      end
      PASS_state: begin
        state_indicator = 4'h4;
      end
      FAIL_state: begin
        state_indicator = 4'h8;
      end
      default: begin
        state_indicator = 4'hf;
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_counter_q <= 1'h0;
    end else begin
      M_counter_q <= M_counter_d;
    end
  end
  
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_state_q <= 1'h0;
    end else begin
      M_state_q <= M_state_d;
    end
  end
  
endmodule
