/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boolean_14 (
    input [15:0] x,
    input [15:0] y,
    input [5:0] alufn,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    
    case (alufn[0+1-:2])
      2'h0: begin
        out = x & y;
      end
      2'h1: begin
        out = x | y;
      end
      2'h2: begin
        out = x ^ y;
      end
      2'h3: begin
        out = x;
      end
      default: begin
        out = 16'h0000;
      end
    endcase
  end
endmodule
