/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compareTester_23 (
    input clk,
    input rst,
    input start,
    input error,
    output reg [3:0] state_indicator,
    output reg [7:0] counter_indicator,
    output reg [1:0] indicator
  );
  
  
  
  reg [5:0] M_counter_d, M_counter_q = 1'h0;
  
  
  localparam SLEEP_state = 2'd0;
  localparam TEST_state = 2'd1;
  localparam PASS_state = 2'd2;
  localparam FAIL_state = 2'd3;
  
  reg [1:0] M_state_d, M_state_q = SLEEP_state;
  
  wire [16-1:0] M_compareUnit_out;
  reg [1-1:0] M_compareUnit_z;
  reg [1-1:0] M_compareUnit_v;
  reg [1-1:0] M_compareUnit_n;
  reg [16-1:0] M_compareUnit_x;
  reg [16-1:0] M_compareUnit_y;
  reg [6-1:0] M_compareUnit_alufn;
  compare_16 compareUnit (
    .z(M_compareUnit_z),
    .v(M_compareUnit_v),
    .n(M_compareUnit_n),
    .x(M_compareUnit_x),
    .y(M_compareUnit_y),
    .alufn(M_compareUnit_alufn),
    .out(M_compareUnit_out)
  );
  
  wire [16-1:0] M_adderUnit_out;
  wire [1-1:0] M_adderUnit_z;
  wire [1-1:0] M_adderUnit_v;
  wire [1-1:0] M_adderUnit_n;
  reg [16-1:0] M_adderUnit_x;
  reg [16-1:0] M_adderUnit_y;
  reg [6-1:0] M_adderUnit_alufn;
  adder_13 adderUnit (
    .x(M_adderUnit_x),
    .y(M_adderUnit_y),
    .alufn(M_adderUnit_alufn),
    .out(M_adderUnit_out),
    .z(M_adderUnit_z),
    .v(M_adderUnit_v),
    .n(M_adderUnit_n)
  );
  
  always @* begin
    M_state_d = M_state_q;
    M_counter_d = M_counter_q;
    
    indicator = 2'h2;
    M_adderUnit_x = 16'h0000;
    M_adderUnit_y = 16'h0000;
    M_adderUnit_alufn = 6'h00;
    M_compareUnit_alufn = 6'h00;
    M_compareUnit_x = 16'h0000;
    M_compareUnit_y = 16'h0000;
    M_compareUnit_z = M_adderUnit_z;
    M_compareUnit_v = M_adderUnit_v;
    M_compareUnit_n = M_adderUnit_n;
    if (start == 1'h0) begin
      M_state_d = SLEEP_state;
      M_counter_d = 1'h0;
    end
    
    case (M_state_q)
      SLEEP_state: begin
        if (start == 1'h1) begin
          M_state_d = TEST_state;
        end
      end
      TEST_state: begin
        
        case (M_counter_q)
          6'h01: begin
            M_compareUnit_alufn = 6'h21;
            M_adderUnit_alufn = 6'h21;
            M_adderUnit_x = 16'h0000;
            M_adderUnit_y = 16'h0000;
            if (error == 1'h1) begin
              if (~M_compareUnit_out[0+0-:1] != 1'h1) begin
                M_state_d = FAIL_state;
              end
            end else begin
              if (M_compareUnit_out[0+0-:1] != 1'h1) begin
                M_state_d = FAIL_state;
              end
            end
          end
          6'h02: begin
            M_compareUnit_alufn = 6'h21;
            M_adderUnit_alufn = 6'h21;
            M_adderUnit_x = 16'h0111;
            M_adderUnit_y = 16'h0111;
            if (M_compareUnit_out[0+0-:1] != 1'h1) begin
              M_state_d = FAIL_state;
            end
          end
          6'h03: begin
            M_compareUnit_alufn = 6'h21;
            M_adderUnit_alufn = 6'h21;
            M_adderUnit_x = 16'hfffd;
            M_adderUnit_y = 16'hfffd;
            if (M_compareUnit_out[0+0-:1] != 1'h1) begin
              M_state_d = FAIL_state;
            end
          end
          6'h04: begin
            M_compareUnit_alufn = 6'h21;
            M_adderUnit_alufn = 6'h21;
            M_adderUnit_x = 16'h0003;
            M_adderUnit_y = 16'h0001;
            if (M_compareUnit_out[0+0-:1] != 1'h0) begin
              M_state_d = FAIL_state;
            end
          end
          6'h05: begin
            M_compareUnit_alufn = 6'h21;
            M_adderUnit_alufn = 6'h21;
            M_adderUnit_x = 16'hf001;
            M_adderUnit_y = 16'h7fff;
            if (M_compareUnit_out[0+0-:1] != 1'h0) begin
              M_state_d = FAIL_state;
            end
          end
          6'h06: begin
            M_compareUnit_alufn = 6'h21;
            M_adderUnit_alufn = 6'h21;
            M_adderUnit_x = 16'hfff9;
            M_adderUnit_y = 16'h0001;
            if (M_compareUnit_out[0+0-:1] != 1'h0) begin
              M_state_d = FAIL_state;
            end
          end
          6'h07: begin
            M_compareUnit_alufn = 6'h21;
            M_adderUnit_alufn = 6'h21;
            M_adderUnit_x = 16'hfffd;
            M_adderUnit_y = 16'hfffe;
            if (M_compareUnit_out[0+0-:1] != 1'h0) begin
              M_state_d = FAIL_state;
            end
          end
          6'h08: begin
            M_compareUnit_alufn = 6'h21;
            M_adderUnit_alufn = 6'h21;
            M_adderUnit_x = 16'h0010;
            M_adderUnit_y = 16'h0008;
            if (M_compareUnit_out[0+0-:1] != 1'h0) begin
              M_state_d = FAIL_state;
            end
          end
          6'h09: begin
            M_compareUnit_alufn = 6'h21;
            M_adderUnit_alufn = 6'h21;
            M_adderUnit_x = 16'h0003;
            M_adderUnit_y = 16'hffff;
            if (M_compareUnit_out[0+0-:1] != 1'h0) begin
              M_state_d = FAIL_state;
            end
          end
          6'h0a: begin
            M_compareUnit_alufn = 6'h21;
            M_adderUnit_alufn = 6'h21;
            M_adderUnit_x = 16'h7fff;
            M_adderUnit_y = 16'hffff;
            if (M_compareUnit_out[0+0-:1] != 1'h0) begin
              M_state_d = FAIL_state;
            end
          end
          6'h0b: begin
            M_compareUnit_alufn = 6'h21;
            M_adderUnit_alufn = 6'h21;
            M_adderUnit_x = 16'hfffe;
            M_adderUnit_y = 16'hfffd;
            if (M_compareUnit_out[0+0-:1] != 1'h0) begin
              M_state_d = FAIL_state;
            end
          end
          6'h0c: begin
            M_compareUnit_alufn = 6'h23;
            M_adderUnit_alufn = 6'h23;
            M_adderUnit_x = 16'h0000;
            M_adderUnit_y = 16'h0000;
            if (M_compareUnit_out[0+0-:1] != 1'h0) begin
              M_state_d = FAIL_state;
            end
          end
          6'h0d: begin
            M_compareUnit_alufn = 6'h23;
            M_adderUnit_alufn = 6'h23;
            M_adderUnit_x = 16'h0010;
            M_adderUnit_y = 16'h0010;
            if (M_compareUnit_out[0+0-:1] != 1'h0) begin
              M_state_d = FAIL_state;
            end
          end
          6'h0e: begin
            M_compareUnit_alufn = 6'h23;
            M_adderUnit_alufn = 6'h23;
            M_adderUnit_x = 16'he000;
            M_adderUnit_y = 16'he000;
            if (M_compareUnit_out[0+0-:1] != 1'h0) begin
              M_state_d = FAIL_state;
            end
          end
          6'h0f: begin
            M_compareUnit_alufn = 6'h23;
            M_adderUnit_alufn = 6'h23;
            M_adderUnit_x = 16'h0060;
            M_adderUnit_y = 16'h0100;
            if (M_compareUnit_out[0+0-:1] != 1'h1) begin
              M_state_d = FAIL_state;
            end
          end
          6'h10: begin
            M_compareUnit_alufn = 6'h23;
            M_adderUnit_alufn = 6'h23;
            M_adderUnit_x = 16'hfff9;
            M_adderUnit_y = 16'h0001;
            if (M_compareUnit_out[0+0-:1] != 1'h1) begin
              M_state_d = FAIL_state;
            end
          end
          6'h11: begin
            M_compareUnit_alufn = 6'h23;
            M_adderUnit_alufn = 6'h23;
            M_adderUnit_x = 16'hf000;
            M_adderUnit_y = 16'h7fff;
            if (M_compareUnit_out[0+0-:1] != 1'h1) begin
              M_state_d = FAIL_state;
            end
          end
          6'h12: begin
            M_compareUnit_alufn = 6'h23;
            M_adderUnit_alufn = 6'h23;
            M_adderUnit_x = 16'hffed;
            M_adderUnit_y = 16'hffee;
            if (M_compareUnit_out[0+0-:1] != 1'h1) begin
              M_state_d = FAIL_state;
            end
          end
          6'h13: begin
            M_compareUnit_alufn = 6'h23;
            M_adderUnit_alufn = 6'h23;
            M_adderUnit_x = 16'h0110;
            M_adderUnit_y = 16'h0100;
            if (M_compareUnit_out[0+0-:1] != 1'h0) begin
              M_state_d = FAIL_state;
            end
          end
          6'h14: begin
            M_compareUnit_alufn = 6'h23;
            M_adderUnit_alufn = 6'h23;
            M_adderUnit_x = 16'h0020;
            M_adderUnit_y = 16'hffff;
            if (M_compareUnit_out[0+0-:1] != 1'h0) begin
              M_state_d = FAIL_state;
            end
          end
          6'h15: begin
            M_compareUnit_alufn = 6'h23;
            M_adderUnit_alufn = 6'h23;
            M_adderUnit_x = 16'h7fff;
            M_adderUnit_y = 16'hffff;
            if (M_compareUnit_out[0+0-:1] != 1'h0) begin
              M_state_d = FAIL_state;
            end
          end
          6'h16: begin
            M_compareUnit_alufn = 6'h23;
            M_adderUnit_alufn = 6'h23;
            M_adderUnit_x = 16'hfeee;
            M_adderUnit_y = 16'hf111;
            if (M_compareUnit_out[0+0-:1] != 1'h0) begin
              M_state_d = FAIL_state;
            end
          end
          6'h17: begin
            M_compareUnit_alufn = 6'h25;
            M_adderUnit_alufn = 6'h25;
            M_adderUnit_x = 16'h0000;
            M_adderUnit_y = 16'h0000;
            if (M_compareUnit_out[0+0-:1] != 1'h1) begin
              M_state_d = FAIL_state;
            end
          end
          6'h18: begin
            M_compareUnit_alufn = 6'h25;
            M_adderUnit_alufn = 6'h25;
            M_adderUnit_x = 16'h0989;
            M_adderUnit_y = 16'h0989;
            if (M_compareUnit_out[0+0-:1] != 1'h1) begin
              M_state_d = FAIL_state;
            end
          end
          6'h19: begin
            M_compareUnit_alufn = 6'h25;
            M_adderUnit_alufn = 6'h25;
            M_adderUnit_x = 16'hf110;
            M_adderUnit_y = 16'hf110;
            if (M_compareUnit_out[0+0-:1] != 1'h1) begin
              M_state_d = FAIL_state;
            end
          end
          6'h1a: begin
            M_compareUnit_alufn = 6'h25;
            M_adderUnit_alufn = 6'h25;
            M_adderUnit_x = 16'h0120;
            M_adderUnit_y = 16'h0180;
            if (M_compareUnit_out[0+0-:1] != 1'h1) begin
              M_state_d = FAIL_state;
            end
          end
          6'h1b: begin
            M_compareUnit_alufn = 6'h25;
            M_adderUnit_alufn = 6'h25;
            M_adderUnit_x = 16'hfff9;
            M_adderUnit_y = 16'h0010;
            if (M_compareUnit_out[0+0-:1] != 1'h1) begin
              M_state_d = FAIL_state;
            end
          end
          6'h1c: begin
            M_compareUnit_alufn = 6'h25;
            M_adderUnit_alufn = 6'h25;
            M_adderUnit_x = 16'hf000;
            M_adderUnit_y = 16'h7fff;
            if (M_compareUnit_out[0+0-:1] != 1'h1) begin
              M_state_d = FAIL_state;
            end
          end
          6'h1d: begin
            M_compareUnit_alufn = 6'h25;
            M_adderUnit_alufn = 6'h25;
            M_adderUnit_x = 16'hf001;
            M_adderUnit_y = 16'hfeee;
            if (M_compareUnit_out[0+0-:1] != 1'h1) begin
              M_state_d = FAIL_state;
            end
          end
          6'h1e: begin
            M_compareUnit_alufn = 6'h25;
            M_adderUnit_alufn = 6'h25;
            M_adderUnit_x = 16'h0888;
            M_adderUnit_y = 16'h0666;
            if (M_compareUnit_out[0+0-:1] != 1'h0) begin
              M_state_d = FAIL_state;
            end
          end
          6'h1f: begin
            M_compareUnit_alufn = 6'h25;
            M_adderUnit_alufn = 6'h25;
            M_adderUnit_x = 16'h0011;
            M_adderUnit_y = 16'hffff;
            if (M_compareUnit_out[0+0-:1] != 1'h0) begin
              M_state_d = FAIL_state;
            end
          end
          6'h20: begin
            M_compareUnit_alufn = 6'h25;
            M_adderUnit_alufn = 6'h25;
            M_adderUnit_x = 16'h7fff;
            M_adderUnit_y = 16'hff99;
            if (M_compareUnit_out[0+0-:1] != 1'h0) begin
              M_state_d = FAIL_state;
            end
          end
          6'h21: begin
            M_compareUnit_alufn = 6'h25;
            M_adderUnit_alufn = 6'h25;
            M_adderUnit_x = 16'hfccc;
            M_adderUnit_y = 16'hfbbb;
            if (M_compareUnit_out[0+0-:1] != 1'h0) begin
              M_state_d = FAIL_state;
            end
          end
          6'h22: begin
            M_state_d = PASS_state;
          end
        endcase
      end
      PASS_state: begin
        indicator = 2'h3;
      end
      FAIL_state: begin
        indicator = 2'h1;
      end
    endcase
    if (M_state_q == TEST_state) begin
      M_counter_d = M_counter_q + 1'h1;
    end
    counter_indicator = M_counter_q;
    
    case (M_state_q)
      SLEEP_state: begin
        state_indicator = 4'h1;
      end
      TEST_state: begin
        state_indicator = 4'h2;
      end
      PASS_state: begin
        state_indicator = 4'h4;
      end
      FAIL_state: begin
        state_indicator = 4'h8;
      end
      default: begin
        state_indicator = 4'hf;
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_state_q <= 1'h0;
    end else begin
      M_state_q <= M_state_d;
    end
  end
  
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_counter_q <= 1'h0;
    end else begin
      M_counter_q <= M_counter_d;
    end
  end
  
endmodule
